#!/command/with-contenv bash

if [ "$SERVICE_ENABLE_HTTP" != "false" ]; then
    set -eo pipefail

    # enforce ulimit like docker <=22 to prevent OOM issues
    # see https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/issues/107
    if [ "$SYSTEM_HTTP_ULIMIT_N" != "-1" ]; then
        ulimit -n "$SYSTEM_HTTP_ULIMIT_N"
    fi

    /usr/sbin/nginx -g "daemon off;"  2>&1 | mawk -W interactive '{printf "%c[32m[http]%c[0m %s\n", 27, 27, $0}'
else
    tail -f /dev/null
fi
