#!/command/with-contenv bash

if [ "$SERVICE_ENABLE_HTTP" != "false" ]; then
    set -eo pipefail
    /httpd-foreground 2>&1 | mawk -W interactive '{printf "%c[32m[http]%c[0m %s\n", 27, 27, $0}'
    # stdbuf ...  --  (remove blank lines from output)
    # awk -W interactive ...  (prefix log messages with color and "[http]")
else
    tail -f /dev/null
fi
