#!/usr/bin/with-contenv bash
if [ "$SERVICE_ENABLE_PIAWARE" != "false" ]
then
	/usr/bin/piaware -plainlog 2>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | mawk -W interactive '{printf "%c[33m [piaware]%c[0m " $0 "\n", 27, 27}'
	# stdbuf ...  --  (remove blank lines from output)
	# awk -W interactive ...  (prefix log messages with color and "[piaware]")
else
	tail -f /dev/null
fi
