#!/command/with-contenv bash

if [ "$SERVICE_ENABLE_PIAWARE" != "false" ]; then
	/usr/bin/piaware -plainlog 2>&1 | mawk -W interactive '{printf "%c[33m [piaware]%c[0m " $0 "\n", 27, 27}'
	# awk -W interactive ...  (prefix log messages with color and "[piaware]")
else
	tail -f /dev/null
fi
