#!/command/with-contenv bash

if [ "$SERVICE_ENABLE_PIAWARE" != "false" ]; then
	default_value() {
		key=${1//\-/_DASH_}
		key=PIAWARE_${key^^}
		eval "value=\${$key:-\$2}"
		printf -v $key -- "$value"
		export $key
	}

	if [ -z "$PIAWARE_FEEDER_DASH_ID" ]; then
		for i in {1..5}; do
			echo "FATAL: PIAWARE_FEEDER_DASH_ID not set!" | mawk -W interactive '{printf "%c[33m[piaware]%c[0m %s\n", 27, 27, $0}'
		done
		kill 1
		exit 1
	fi

	default_value "feeder-id" "YOUR_FEEDER_ID"
	default_value "receiver-type" "other"
	default_value "receiver-host" "127.0.0.1"
	default_value "receiver-port" "30005"

	if [ ! -f /etc/piaware.conf ]; then
		/opt/confd/bin/confd -onetime -confdir "/etc/confd/piaware" -prefix "piaware" -backend env
	fi
fi
