#!/command/with-contenv bash

set -eo pipefail

/usr/local/share/adsbexchange/json-status 2>&1 | mawk -W interactive '{printf "%c[32m[adsbexchange-stats]%c[0m %s\n", 27, 27, $0}'

# awk -W interactive ...  (prefix log messages with color and "[adsbexchange-stats]")
