#!/command/with-contenv bash

if [ "$SERVICE_ENABLE_HTTP" != "false" ]; then
	default_value() {
		key=${1//\-/_DASH_}
		key=HTML_${key^^}
		eval "value=\${$key:-\$2}"
		printf -v $key -- "$value"
		export $key
	}

	default_value "site_lat" "45.0"
	default_value "site_lon" "9.0"
	default_value "site_name" "My Radar Site"
	default_value "default_tracker" "FlightAware"
	default_value "receiver_stats_page_flightaware" ""
	default_value "receiver_stats_page_flightradar24" ""
	default_value "receiver_stats_page_adsbexchange" ""
	default_value "receiver_stats_page_planefinder" ""
	default_value "receiver_stats_page_opensky_network" ""
	default_value "receiver_stats_page_adsbfi" ""
	default_value "receiver_stats_page_adsbhub" ""
	default_value "fr24_feeder_status_page" ""

	if [ ! -f /usr/lib/fr24/public_html/config.js ]; then
		/opt/confd/bin/confd -onetime -confdir "/etc/confd/html" -prefix "html" -backend env
	fi
fi
