#!/usr/bin/with-contenv bash
if [ "$SERVICE_ENABLE_IMPORT_OVER_NETCAT" != "false" ]
then
	echo "Waiting until dump1090 is listening on configured network port..."
	while ! nc -z localhost ${DUMP1090_LOCAL_PORT}; do sleep 1; done
	echo "dump1090 port is available now. Start forwarding..."
	/bin/nc ${DUMP1090_REMOTE_HOST} ${DUMP1090_REMOTE_PORT} | /bin/nc -q1 localhost ${DUMP1090_LOCAL_PORT}
else
	tail -f /dev/null
fi
