#!/usr/bin/with-contenv bash
if [ "$SERVICE_ENABLE_DUMP1090" != "false" ]
then
	default_value() 
	{ 
		key=${1//\-/_DASH_}
		key=HTML_${key^^}
		eval "value=\${$key:-\$2}"
		printf -v $key -- "$value"
		export $key
	}
	default_value "site_lat" "45.0"
	default_value "site_lon" "9.0"
	/bin/decoration -c yellow -p "[dump1090] " -e "/usr/lib/fr24/dump1090" -a "--net --write-json /usr/lib/fr24/public_html/data --raw --quiet --lat ${HTML_SITE_LAT} --lon ${HTML_SITE_LON}"
else
	tail -f /dev/null
fi
