#!/command/with-contenv bash

if [ "$SERVICE_ENABLE_FR24FEED" != "false" ]; then
	default_value() {
		key=${1//\-/_DASH_}
		key=FR24FEED_${key^^}
		eval "value=\${$key:-\$2}"
		printf -v $key -- "$value"
		export $key
	}

	if [ -z "$FR24FEED_FR24KEY" ]; then
        for i in {1..5}; do
            echo "FATAL: FR24FEED_FR24KEY not set!" | mawk -W interactive '{printf "%c[34m[fr24feed]%c[0m %s\n", 27, 27, $0}'
        done
        kill 1
        exit 1
    fi

	default_value "receiver" "beast-tcp"
	default_value "fr24key" "YOUR_KEY_HERE"
	default_value "host" "127.0.0.1:30005"
	default_value "bs" "no"
	default_value "raw" "no"
	default_value "logmode" "1"
	default_value "logpath" "/tmp"
	default_value "mlat" "yes"
	default_value "mlat-without-gps" "yes"

	if [ ! -f /etc/fr24feed.ini ]; then
		/opt/confd/bin/confd -onetime -confdir "/etc/confd/fr24feed" -prefix "fr24feed" -backend env
	fi
fi
