#!/command/with-contenv bash

if [ "$SERVICE_ENABLE_PLANEFINDER" != "false" ]; then
    set -eo pipefail

    default_value() {
        key=${1//\-/_DASH_}
        key=PLANEFINDER_${key^^}
        eval "value=\${$key:-\$2}"
        printf -v $key -- "$value"
        export $key
    }

    default_value "input_host" "127.0.0.1"
    default_value "input_port" "30005"

    if [ -z "$PLANEFINDER_SHARECODE" ]; then
        for i in {1..5}; do
            echo "FATAL: PLANEFINDER_SHARECODE not set!" | mawk -W interactive '{printf "%c[36m[planefinder]%c[0m %s\n", 27, 27, $0}'
        done
        kill 1
        exit 1
    fi

    # Ensure config exist
    mkdir -p /planefinder/config

    # Ensure log exist
    mkdir -p /planefinder/log

    # Ensure pid file exists
    touch /run/pfclient.pid
fi