#!/usr/bin/with-contenv bash
if [ "$SERVICE_ENABLE_HTTP" != "false" ]
then
	cd /usr/lib/fr24/public_html
	/bin/decoration -c cyan -p "[http] " -e "/usr/bin/python3" -a "-m http.server 8080"
else
	tail -f /dev/null
fi