#!/usr/bin/with-contenv bash

default_value() 
{ 
	key=${1//\-/_DASH_}
	key=PIAWARE_${key^^}
	eval "value=\${$key:-\$2}"
	printf -v $key "$value"
	export $key
}

default_value "feeder-id" "YOUR_FEEDER_ID"
default_value "receiver-type" "other"
default_value "receiver-host" "127.0.0.1"
default_value "receiver-port" "30005"

if [ ! -f /etc/piaware.conf ]; then
	/opt/confd/bin/confd -onetime -confdir "/etc/confd/piaware" -prefix "piaware" -backend env
fi