#!/usr/bin/with-contenv bash

default_value() 
{ 
	key=${1//\-/_DASH_}
	key=HTML_${key^^}
	eval "value=\${$key:-\$2}"
	printf -v $key -- "$value"
	export $key
}

default_value "site_lat" "45.0"
default_value "site_lon" "9.0"
default_value "site_name" "My Radar Site"
default_value "default_tracker" "FlightAware"

if [ ! -f /usr/lib/fr24/public_html/config.js ]; then
	/opt/confd/bin/confd -onetime -confdir "/etc/confd/html" -prefix "html" -backend env
fi